### ISSUE TITLE
GSMViewer issue when selecting Chromosome

### ISSUE THREAD

**Issue by mattknowles314** [mattknowles314/bspi2020#1]
Line 36 in GSMViewer: If you select the chromosome as "1", it will give you not only chr1, but chr11, chr12 etc. I've tried fixing this by checking the 5th index for an empty string but this didn't work.

**Comment by eleanorsabey** [comment]
try 4th index? if first index = position 0

**Comment by mattknowles314** [comment]
The issue with that is checking up to index 4 means looking to see if chromosome == "chr1 ", when i tried this by concatonating " " to the end, it didn't work but im not sure why. I will have a look at this in the morning though.

**Comment by mattknowles314** [comment]
Good news, this has now been fixed. Instead of manually checking each individual character as an index, it now splits the whole row into a list and checks the first index of that  list for the chromosome name.
This is great because splitting to a list earlier will make the program more efficient, as I don't need to do it again in the second for loop later on, so hopefully it will run faster now too, which will be handy when dealing with huge datasets.
